get http://localhost:8000/hello

###
get http://localhost:8000/142857

###
get http://localhost:8000/qs?p1=2&p2=ass_ass_in's_creed

###
post http://localhost:8000/hello

###
post http://localhost:8000/post-req
Content-Type: application/json; charset=UTF-8

{
    "name":"Rose",
    "age" : 20
}

###
get http://localhost:8000/nations/list

###
get http://localhost:8000/nations/4

###
post http://localhost:8000/nations/save
Content-Type: application/json; charset=UTF-8

{
    "name":"Italia",
    "capital":"Rome",
    "population":60390000
}

###
put http://localhost:8000/nations/1
Content-Type: application/json; charset=UTF-8

{
    "id" : 1,
    "name" : "Korea",
    "capital" : "Seoul",
    "population" : 51100000
}

###
delete http://localhost:8000/nations/5
Content-Type: application/json; charset=UTF-8